### PR TITLE
[UPDATE]: Changing colors, adding `defer` field

### PR DESCRIPTION
**Pull request by Soumyajit0803**
### Description
This is a testing PR where I have changed the color of table and added `defer` field in `script` tag The defer should make the `script` tag run after the elements were rendered. 

### Language used
* `HTML`
* `CSS`
### Type of change: 
* `Enhancement`

### CODE REVIEW

**Comment by Asif-Tanvir-2006** [comment]
Capitalise the letters of the title, i.e,  "Leaderboard" -> "LEADERBOARD"

**Comment by Soumyajit0803** [comment]
> Capitalise the letters of the title, i.e, "Leaderboard" -> "LEADERBOARD"

Okay on it 👍

**Comment by Soumyajit0803** [comment]
I did the changes!

**Comment by Asif-Tanvir-2006** [comment]
Getting rid of this PR

**Pull request closed without merging**
